### ISSUE TITLE
Unable to publish snapshot after initial upload

### ISSUE THREAD

**Issue by slomo** [jcaddel/maven-s3-wagon#15]
Hi,

I am using the s3-wagon thorugh [gradle](https://github.com/fidesmo/gradle-fidesmo/blob/a761460690bc98ab52b394daf91c243ef6a6707e/build.gradle) and the gradle maven plugin. Initially I deployed from my machine, but then moved the deployment to traviCI, were I encountered a [stacktrace](https://travis-ci.org/fidesmo/gradle-fidesmo/builds/33266183#L144).

```
Transfer error: java.io.FileNotFoundException: /home/travis/.m2/repository/com/fidesmo/gradle-fidesmo/0.1-SNAPSHOT/maven-metadata-remote.xml.tmp (No such file or directory)
java.io.FileNotFoundException: /home/travis/.m2/repository/com/fidesmo/gradle-fidesmo/0.1-SNAPSHOT/maven-metadata-remote.xml.tmp (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
    at org.kuali.maven.wagon.TransferProgressFileOutputStream.<init>(TransferProgressFileOutputStream.java:35)
    at org.kuali.maven.wagon.S3Wagon.getResource(S3Wagon.java:242)
    at org.kuali.maven.wagon.AbstractWagon.get(AbstractWagon.java:171)
    at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:546)
    at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifactMetadataFromDeploymentRepository(DefaultWagonManager.java:452)
    at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.getArtifactMetadataFromDeploymentRepository(DefaultRepositoryMetadataManager.java:379)
    at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:347)
    at 
```

Which I would have expected since I never used the local maven repository while deploying. This issue only arises if there this was not the first deployment of the artifact and was reproducible from my workstation, when removing the `~/.m2` directory.

Since I am quite new to the eco system, I don't know whether this is an issue of the wagon or the maven plugin for gradle. So I filed  the bug here. My current quick fix is to first run `gradle install` which will deploy to the local repository.

**Comment by daanemanz** [comment]
@slomo are you still seeing this issue? I fixed it by installing a more recent version of Gradle -- more specifically I upgraded from `2.4` to `2.9`.
